dleitee - Git Instructions
CheesecakeLabs/react-next-boilerplate pull request #1
Opened 2018-05-02 15:39 UTC by dleitee

# Features

- Add how to configure git when we are starting a project.

ps: please, give me feedback on the text.

2018-05-02 17:21 UTC, accordeiro requested changes

2018-05-02 17:21 UTC, accordeiro commented on README.md
> +This part is so much important to start a project and you have a mission to sync with your PM about the repository on the Github/Bitbucket.
Hi! I'd change "you have a mission to sync.. etc." with "you should check your PM what repo you should use as the official one for the project". What do you think? :)

2018-05-02 17:21 UTC, accordeiro commented on README.md
> +This part is so much important to start a project and you have a mission to sync with your PM about the repository on the Github/Bitbucket.
Also, in this file, but on the first comment, what do you think about replacing "anxious" with "excited"? :)

2018-05-02 17:21 UTC, accordeiro commented on README.md
> +At the first time, we gonna start our local git repository:
If you've just cloned the repo, you probably already have the git initialized, right? We probably only need to replace the remote. Makes sense?

2018-05-02 17:21 UTC, accordeiro commented on README.md
> +
I'd add a note stating how important this is. Something like:

`This part is very important, since you don't want to create branches / commits on top of the boilerplate, but rather on top of the new project's repo.`

How does that sound? :)

2018-06-02 18:35 UTC, gdevincenzi commented on README.md
> +
Very important, and easy to forget.

2018-06-04 11:21 UTC, dleitee commented on README.md
> +
on the `create-ckl-react-app` this is done by default

2018-06-20 12:45 UTC, douglasgimli approved these changes

2018-07-25 21:21 UTC, dleitee commented
we don't need it anymore

2018-07-25 21:21 UTC, closed without merging