Pattyssilveira/modal window component
CheesecakeLabs/react-next-boilerplate pull request #14
Opened 2018-07-20 15:09 UTC by pattyssilveira

This PR adds : 
- Modal window
- Modal header
- Modal body
- Modal footer
- Close button 
- Full-width button

2018-07-23 17:03 UTC, dleitee requested changes

2018-07-23 17:03 UTC, dleitee commented on src/components/atoms/modal-header/index.js
> +// import CloseIcon from '_atoms/close-icon'
?

2018-07-24 12:50 UTC, beatriz1304 commented on src/components/atoms/modal-body/styles.css
> +    color: #666666;
Put that inside ``css-variables.js`` file

2018-07-24 12:52 UTC, beatriz1304 commented on src/components/atoms/modal-footer/index.js
> +import classNames from 'classnames/bind'
Remove the bind it's not necessary 
``import classNames from 'classnames'``

2018-07-24 12:55 UTC, beatriz1304 commented on src/components/atoms/modal/index.js
> +class Modal extends React.Component {
You can import `Component` from react lib and then just you here

`class Modal extends Component`

2018-07-24 12:55 UTC, beatriz1304 commented on src/components/atoms/modal/index.js
> +import React from 'react'
import here the `Component` class

`import React, {Component} from 'react' `

2018-07-24 12:56 UTC, beatriz1304 commented on src/components/atoms/modal/index.js
> +  constructor() {
With ES6 it's not necessary use the constructor and calling the super

2018-07-24 12:59 UTC, beatriz1304 commented on src/components/atoms/modal/index.js
> +  constructor() {
You can just declare your state like:
`state = {modalIsOpen: true}`

2018-07-27 13:53 UTC, closed without merging