Feature: input components
CheesecakeLabs/react-next-boilerplate pull request #25
Opened 2018-07-27 19:50 UTC by mibsbalsante

2018-07-30 15:52 UTC, dleitee requested changes

2018-07-30 15:52 UTC, dleitee commented on components/atoms/input/index.js
> +  handleChange: PropTypes.func.isRequired,
I think that `handleChange` should be optional and the default should be `() => {}`

2018-07-30 15:52 UTC, dleitee commented on components/molecules/checkbox/index.js
> +  id: PropTypes.string.isRequired,
none of it should be required.

2018-07-30 15:52 UTC, dleitee commented on components/molecules/radio/index.js
> +  id: PropTypes.string.isRequired,
none of it should be required.

2018-07-30 15:52 UTC, dleitee commented on src/images/check.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="7" height="5" viewBox="0 0 7 5">
move it to `components/assets/...`

2018-07-30 16:39 UTC, mibsbalsante commented
@dleitee can you check if is everything ok now, please? 😄

2018-07-30 16:43 UTC, beatriz1304 commented on components/molecules/radio/index.stories.js
> +import React from 'react'
Import Component here like
`import React, {Component} from 'react'`

2018-07-30 16:44 UTC, beatriz1304 commented on components/molecules/radio/index.stories.js
> +import React from 'react'
You are using Fragment too 
import React, {Component, Fragment} from 'react'

2018-07-30 16:45 UTC, beatriz1304 commented on components/molecules/radio/index.stories.js
> +CustomRadioGroup.propTypes = {
Put prop validation inside the class

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/radio/index.stories.js
> +CustomRadioGroup.propTypes = {
Do that with the default Props too

2018-07-30 16:58 UTC, beatriz1304 commented on src/config/css-variables.js
> +styles['color-text'] = '#000'
We need to define the color pallette, remember that we've talked about the color variable names like `color-primary, color-primary-dark ` and so on

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/checkbox/index.js
> +    <label className={styles.checkbox} role="checkbox" aria-checked={isChecked}>
I think this label could be a separated component that will receive a children

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/checkbox/index.js
> +      <Input {...props} type="checkbox" className={inputClasses} checked={isChecked} />
There was a PR mine that DLeite told me to remove the `...props` and write down all the properties to be clear for the user what he really needs to send

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/checkbox/index.js
> +  isChecked: PropTypes.bool.isRequired,
In this line you put that property is required and on the `defaultProps` you attributed a value for this.

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/checkbox/index.stories.js
> +class CustomCheckboxGroup extends React.Component {
Import `Components`

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/checkbox/index.stories.js
> +  handleChange = e => {
Change the parameter name to be clear from `e` to `event` or other thing

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/checkbox/index.stories.js
> +    <React.Fragment>
Import `Fragment`

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/checkbox/index.stories.js
> +          name: 'checkbox[]',
All the child will have the same name? Is it correctly?

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/radio/styles.css
> +      box-shadow: 0 0px 1px 1px #91d0d9;
Use this color as a var

2018-07-30 16:58 UTC, beatriz1304 commented on components/molecules/radio/styles.css
> +    background: white;
Use that color as a var

2018-07-31 20:20 UTC, dleitee submitted a review, later dismissed
Awesome!!!!

2018-07-31 20:20 UTC, dleitee commented on components/molecules/checkbox/index.stories.js
> +class CustomCheckboxGroup extends Component {
We can move it to components later, what do you think?

2018-07-31 20:58 UTC, beatriz1304 approved these changes

2018-07-31 20:58 UTC, merged

2018-07-31 20:58 UTC, mibsbalsante commented on components/molecules/checkbox/index.stories.js
> +class CustomCheckboxGroup extends Component {
We can try it in the future 🎉