Pattyssilveira/accordion component
CheesecakeLabs/react-next-boilerplate pull request #26
Opened 2018-07-30 18:55 UTC by pattyssilveira

This pt adds:
- Accordion section component
- Accordion component
- Accordion Storybook

2018-07-31 13:15 UTC, beatriz1304 commented on components/atoms/accordion-section/index.js
> +        <button className={styles.header} onClick={this.handleClick}>
Change button to a component 
We've already implemented this

2018-07-31 13:15 UTC, beatriz1304 commented on components/atoms/accordion-section/styles.css
> +    background-color: white;
Use color as a variable

2018-07-31 13:16 UTC, beatriz1304 commented on components/atoms/accordion-section/styles.css
> +    color: #979797;
Same here

2018-07-31 13:16 UTC, beatriz1304 commented on components/atoms/accordion-section/styles.css
> +   color: #4c4c4c;
Same here

2018-07-31 13:16 UTC, beatriz1304 commented on components/atoms/accordion-section/styles.css
> +    background-color: #f5f6f6;
Use all colors as a variable

2018-07-31 13:18 UTC, beatriz1304 commented on components/atoms/accordion-section/index.js
> +Section.propTypes = {
I think you should put this code as a static property inside class

`static propTypes = {}`

2018-07-31 13:19 UTC, beatriz1304 commented on components/atoms/accordion-section/index.js
> +Section.defaultProps = {
Same with the default props

`static defaultProps = {
    isOpen: true,
    onClick: () => {},
     ...
  }`

2018-07-31 13:21 UTC, beatriz1304 commented on components/atoms/accordion-section/styles.css
> +    transition: height 0.5s;
Just for information, it's possible to use `.5s` without 0

2018-07-31 13:22 UTC, beatriz1304 commented on components/molecules/accordion/index.js
> +  isOpen: false,
Remove the unused props

2018-07-31 13:28 UTC, beatriz1304 commented on components/atoms/accordion-section/index.js
> +        <div className={styles.body} ref={this.bodyRef} style={{ height }}>
I don't know if it's a good idea to have className and style both as props
We can talk more about this with Doug, DLeite and Mibs

2018-07-31 13:32 UTC, beatriz1304 commented on components/atoms/accordion-section/index.js
> +          <i className={iconClass} />
I think that can have more components

2018-07-31 14:27 UTC, dleitee requested changes

2018-07-31 14:27 UTC, dleitee commented on components/atoms/accordion-section/index.js
> +class Section extends Component {
move section to `/accordion/section.js`

2018-07-31 14:27 UTC, dleitee commented on components/atoms/accordion-section/index.js
> +  handleClick = () => {
I have to think about it.

2018-07-31 14:27 UTC, dleitee commented on components/atoms/accordion-section/index.js
> +  bodyRef = element => {
I have to think about it.

2018-07-31 14:27 UTC, dleitee commented on components/atoms/accordion-section/styles.css
> +    transition: height 0.5s;
we need to create a stylelint as well

2018-07-31 14:27 UTC, dleitee commented on components/molecules/accordion/index.js
> +const Accordion = ({ children }) => <div className={styles.accordion}>{children}</div>
add `Accordion.Section = Section`

2018-07-31 14:27 UTC, dleitee commented on components/molecules/accordion/index.js
> +import styles from './styles.css'
add `import Section from './section'`

2018-07-31 14:27 UTC, dleitee commented on components/molecules/accordion/index.stories.js
> +    <Section sectionTitle="Neymar"> O ousado chegou.</Section>
use `Accordion.Section`

2018-08-01 18:33 UTC, pattyssilveira commented
@dleitee @beatriz1304 I made some changes, can you review again? =)

2018-08-06 19:27 UTC, dleitee approved these changes

2018-08-06 20:26 UTC, merged